### ISSUE TITLE
New scoresaber site has removed support for this extension.

### ISSUE THREAD

**Issue by andrewhong04** [JakeCover/ScoreSaverExtention#2]
![image](https://user-images.githubusercontent.com/35881688/143503474-bd859569-400f-43b1-b19c-fa832714a450.png)

**Comment by Cobular** [comment]
Ah shoot, thanks for bringing this up! I'll work on getting it fixed over the weekend.

**Comment by Cobular** [comment]
Great, new version is now pending release for chrome and firefox. That usually takes a day or two, you can try to load from this zip if you'd like to test things out yourself:
[scoresaber_easy_installer-2.0.zip](https://github.com/Cobular/ScoreSaverExtention/files/7611609/scoresaber_easy_installer-2.0.zip)

I've tested it a bit but it's also 3 AM so I could have missed a bug somewhere! Plz let me know if there's any follow-up.

**Comment by andrewhong04** [comment]
> Great, new version is now pending release for chrome and firefox. That usually takes a day or two, you can try to load from this zip if you'd like to test things out yourself:
> [scoresaber_easy_installer-2.0.zip](https://github.com/Cobular/ScoreSaverExtention/files/7611609/scoresaber_easy_installer-2.0.zip)
> 
> I've tested it a bit but it's also 3 AM so I could have missed a bug somewhere! Plz let me know if there's any follow-up.

Thanks!

**Comment by Cobular** [comment]
Following up on this, any issues or concerns?

**Comment by andrewhong04** [comment]
> Following up on this, any issues or concerns?

Sorry, I've been very busy with school so far. I'll try it out after-school today.

Edit: I see the button at least.

**Comment by andrewhong04** [comment]
Looks like it's fixed! Thanks!!
