### ISSUE TITLE
Button isn't showing

### ISSUE THREAD

**Issue by Gami13** [JakeCover/ScoreSaverExtention#3]
![image](https://user-images.githubusercontent.com/71034355/147501152-f30e16a4-829a-4922-9efa-2c4ab09f5fce.png)

The download button isn't showing up

**Comment by Cobular** [comment]
Will investigate in a bit! What browser are you using?

**Comment by Gami13** [comment]
tried it on both edge and chrome

**Comment by Cobular** [comment]
Cool, they broke it when they added the amazon music thing. I've made some of the detection more robust now, works again and should break less in the future. Pushing to stores now, should be updated by EOD.
