### ISSUE TITLE
Does not work - undefined hash

### ISSUE THREAD

**Issue by MiChAeLoKGB** [JakeCover/ScoreSaverExtention#4]
Hi,

seems like SkoreSaber has added an icon  to their hash element and thanks to that (and the whitespace between the icon and the hash), the code stopped working (because your call to `api.beatsaver.com` starts with `%20`
To fix that, all you need is to change
```
let song_hash = hash_element.textContent;
```

to 

```
let song_hash = hash_element.textContent.trim();
```

I have currently plopped the code to custom Tamper monkey script and it's working like a charm.

**Comment by Cobular** [comment]
Thank you so much! The email notification for this got lost in the void, but I'll get on this later today. Thank you so much for figuring out exactly what was up and needs to be changed!!
